### ISSUE TITLE
Actually update Slack information when endpoints are called

### ISSUE THREAD

**Issue by ivanmayes** [botpress/botpress-slack#11]
It appears that the module connects to slack and gets slack's current info which is great, however the longer a bot is running, the more out of date that information can get.  

We are working on an implementation with looking for the right channel for a piece of information, but the channels get outdated and it inhibits being able to provide real time features to users.

**Comment by ivanmayes** [comment]
Looks like this area just needs to get replaced.  Sorry I would have made a pull request but all i could do was edit the node module bundle with all the transpiled code, so wanted to make sure someone else tested before pushing.

https://github.com/botpress/botpress-slack/blob/master/src/slack.js#L205

```
getChannels() {
var url = 'https://slack.com/api/channels.list' + '?token=' + this.config.apiToken;
return axios.get(url).then(({data}) => {

	        if (!data.ok) {
	          throw new Error('Error getting channels:' + data);
	        }
	
	        return data.channels;
})
}
```

**Comment by DanyFS** [comment]
@ivanmayes Thanks for the report and suggestion! I just tested your code and push it.

Next time if you want to make a PR, you can fork the repository and modify it directly.

You will need to install and link your own version of the module to your bot. You can to it easily by using: ` bp install /{PATH}/botpress-slack && npm link /{PATH}/botpress-slack`

And while you are making changes to the module, you will need to compile it. There's already a script for that in each module: `npm run compile` or `npm run watch` for real-time recompiling.

Thanks again!

**Comment by slvnperron** [comment]
@DanyFS can this be closed then?
