### ISSUE TITLE
Feature Request: Refactor action-endpoint incoming messages to support menus (and future actions)

### ISSUE THREAD

**Issue by ivanmayes** [botpress/botpress-slack#17]
Hey guys!  Since Slack has come out with menu actions, I was looking into adding some distinctions to set between menus and buttons so that it would be easier to use bp.hear to match them.  Here's what is there today:

```
bp.middlewares.sendIncoming({
        platform: 'slack',
        type: 'button',
        text: user.profile.real_name + ' clicked on a button',
        user: user,
        channel: payload.channel,
        button: payload.actions[0],
        ts: payload.message_ts,
        direct: isDirect(payload.channel.id),
        raw: payload
      })
```

The biggest thing that would be breaking would be refactoring the button property into action, then switching the `type` and `text` between button and menu states.  Also, Slack recommends using the `callback_id` to determine a unique path for functionality.

**Comment by ivanmayes** [comment]
Committed #18 to address callback_id, just need to discuss if there needs to be any breaking refactors to support both button and menu callouts in the rest of the object

**Comment by slvnperron** [comment]
@ivanmayes That makes sense! Since this is breaking, what about we send a second event for actions and deprecate the `button` action in Botpress 1.0?

**Comment by ivanmayes** [comment]
@slvnperron Sounds good, I'll set that up.
